# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dongyuchun/Desktop/Screenshot/ScreenshotUI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selpathButton = QtWidgets.QPushButton(self.centralwidget)
        self.selpathButton.setGeometry(QtCore.QRect(270, 360, 91, 31))
        self.selpathButton.setObjectName("selpathButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(410, 360, 112, 32))
        self.saveButton.setObjectName("saveButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 211, 399))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout.addWidget(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout.addWidget(self.radioButton_16)
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_17.setObjectName("radioButton_17")
        self.verticalLayout.addWidget(self.radioButton_17)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 291, 301))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pathEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathEdit.setGeometry(QtCore.QRect(260, 330, 281, 21))
        self.pathEdit.setObjectName("pathEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "辅助截图软件1.0"))
        self.selpathButton.setText(_translate("MainWindow", "选择路径"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.groupBox.setTitle(_translate("MainWindow", "选择区域"))
        self.checkBox.setText(_translate("MainWindow", "锁定"))
        self.radioButton_2.setText(_translate("MainWindow", "CIC-坏死"))
        self.radioButton.setText(_translate("MainWindow", "CIC-影细胞"))
        self.radioButton_3.setText(_translate("MainWindow", "CIC-间质粘液样"))
        self.radioButton_4.setText(_translate("MainWindow", "CIC-细胞稀疏"))
        self.radioButton_5.setText(_translate("MainWindow", "CIC-泡沫细胞"))
        self.radioButton_6.setText(_translate("MainWindow", "CIC-含铁血黄素"))
        self.radioButton_7.setText(_translate("MainWindow", "CIC-泡沫细胞及含铁血黄素"))
        self.radioButton_8.setText(_translate("MainWindow", "CIC-钙化"))
        self.radioButton_9.setText(_translate("MainWindow", "CIC-肉芽"))
        self.radioButton_10.setText(_translate("MainWindow", "CIC-炎症"))
        self.radioButton_11.setText(_translate("MainWindow", "CIC"))
        self.radioButton_12.setText(_translate("MainWindow", "T-上皮"))
        self.radioButton_13.setText(_translate("MainWindow", "T-间液"))
        self.radioButton_14.setText(_translate("MainWindow", "T-胚芽"))
        self.radioButton_15.setText(_translate("MainWindow", "T-间变细胞"))
        self.radioButton_16.setText(_translate("MainWindow", "0-肾实质"))
        self.radioButton_17.setText(_translate("MainWindow", "0-血管脂肪"))

